AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String

  ALBSecurityGroup:
    Type: String

  HTTPPort:
    Type: Number

  PublicSubnet1:
    Type: String

  PublicSubnet2:
    Type: String

  VPC:
    Type: String

  HealthyThresholdCount:
    Type: Number

  UnhealthyThresholdCount:
    Type: Number

  HealthCheckTimeoutSeconds:
    Type: Number

  HealthCheckIntervalSeconds:
    Type: Number

  HttpCode:
    Type: Number


Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${ProjectName}-ALB
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Type: application
      # LoadBalancerAttributes:
      #   - Key: access_logs.s3.enabled
      #     Value: true
      #   - Key: access_logs.s3.bucket
      #     Value: !Ref ALBlogbucket
      #   - Key: access_logs.s3.prefix
      #     Value: !Ref ALBlogbucketprefix

  ALBTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
      Name: !Sub ${ProjectName}-ALBTargetGroup
      Protocol: HTTP
      Port: !Ref HTTPPort
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthyThresholdCount: !Ref HealthyThresholdCount
      UnhealthyThresholdCount: !Ref UnhealthyThresholdCount
      HealthCheckTimeoutSeconds: !Ref HealthCheckTimeoutSeconds
      HealthCheckIntervalSeconds: !Ref HealthCheckIntervalSeconds
      Matcher:
        HttpCode: !Ref HttpCode
      TargetType: ip

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref ALBTargetGroup
          Type: forward
      LoadBalancerArn: !Ref ALB
      Port: !Ref HTTPPort
      Protocol: HTTP


Outputs:
  ALBTargetGroup:
    Value: !Ref ALBTargetGroup

  ALBEndpoint:
    Value: !Sub "http://${ALB.DNSName}"
