AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String

  ALBSecurityGroup:
    Type: String

  HTTPPort:
    Type: Number

  PublicSubnet1:
    Type: String

  PublicSubnet2:
    Type: String

  VPC:
    Type: String

  HealthyThresholdCount:
    Type: Number

  UnhealthyThresholdCount:
    Type: Number

  HealthCheckTimeoutSeconds:
    Type: Number

  HealthCheckIntervalSeconds:
    Type: Number

  HttpCode:
    Type: Number


Resources:
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${ProjectName}-ALB
      Scheme: internet-facing
      SecurityGroups:
        - !Ref ALBSecurityGroup
      Subnets:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      Type: application
      # Log欲しい場合
      # LoadBalancerAttributes:
      #   - Key: access_logs.s3.enabled
      #     Value: true
      #   - Key: access_logs.s3.bucket
      #     Value: !Ref ALBlogbucket
      #   - Key: access_logs.s3.prefix
      #     Value: !Ref ALBlogbucketprefix

#=================================
#  For Blue/Green Update (ProdTrafficRoute)
#=================================
  ALBTargetGroupBlue:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
      Name: !Sub ${ProjectName}-ALBTargetGroupBlue
      Protocol: HTTP
      Port: !Ref HTTPPort
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthyThresholdCount: !Ref HealthyThresholdCount
      UnhealthyThresholdCount: !Ref UnhealthyThresholdCount
      HealthCheckTimeoutSeconds: !Ref HealthCheckTimeoutSeconds
      HealthCheckIntervalSeconds: !Ref HealthCheckIntervalSeconds
      Matcher:
        HttpCode: !Ref HttpCode
      TargetType: ip

  ALBListenerBlue:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref ALBTargetGroupBlue
          Type: forward
      LoadBalancerArn: !Ref ALB
      Port: !Ref HTTPPort
      Protocol: HTTP

#=================================
#  For Blue/Green Update (TestTrafficRoute)
#=================================
  ALBTargetGroupGreen:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VPC
      Name: !Sub ${ProjectName}-ALBTargetGroupGreen
      Protocol: HTTP
      Port: !Ref HTTPPort
      HealthCheckProtocol: HTTP
      HealthCheckPath: /
      HealthCheckPort: traffic-port
      HealthyThresholdCount: !Ref HealthyThresholdCount
      UnhealthyThresholdCount: !Ref UnhealthyThresholdCount
      HealthCheckTimeoutSeconds: !Ref HealthCheckTimeoutSeconds
      HealthCheckIntervalSeconds: !Ref HealthCheckIntervalSeconds
      Matcher:
        HttpCode: !Ref HttpCode
      TargetType: ip

  ALBListenerGreen:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn: !Ref ALBTargetGroupGreen
          Type: forward
      LoadBalancerArn: !Ref ALB
      Port: 10080
      Protocol: HTTP


Outputs:
  ALBTargetGroupBlue:
    Value: !Ref ALBTargetGroupBlue
  ALBTargetGroupGreen:
    Value: !Ref ALBTargetGroupGreen
  ALBListenerBlue:
    Value: !Ref ALBListenerBlue
  ALBListenerGreen:
    Value: !Ref ALBListenerGreen

  ALBEndpoint:
    Value: !Sub "http://${ALB.DNSName}"
