version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: aws/task-definition.json
        PlatformVersion: 1.4.0
        LoadBalancerInfo:
            ContainerName: soda-2022-08-container
            ContainerPort: 3000
