AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ProjectName:
    Type: String
    Default: soda-2022-07

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ProjectName


Outputs:
  ECRRepository:
    Value: !GetAtt ECRRepository.RepositoryUri
