AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  ProjectName:
    Type: String

Resources:
  ECRRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ProjectName


Outputs:
  ECRRepository:
    Value: !GetAtt ECRRepository.RepositoryUri
  ECRRepositoryArn:
    Value: !GetAtt ECRRepository.Arn
