AWSTemplateFormatVersion: 2010-09-09

Parameters:
  ProjectName:
    Type: String

  AvailabilityZone:
    Type: String

  DBAllocatedStorage:
    Type: Number

  DBEngine:
    Type: String

  DBEngineVersion:
    Type: String

  DBInstanceClass:
    Type: String

  DBMasterUsername:
    Type: String

  DBMasterUserPassword:
    Type: String

  PrivateSubnet1:
    Type: String

  PrivateSubnet2:
    Type: String

  DBSecurityGroup:
    Type: String


Resources:
  DBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: "prod"
      AllocatedStorage: !Ref DBAllocatedStorage
      AvailabilityZone: !Sub "${AWS::Region}${AvailabilityZone}"
      DBInstanceClass: !Ref DBInstanceClass
      DBInstanceIdentifier: !Sub "${ProjectName}-DBInstance"
      DBSubnetGroupName: !Ref DBSubnetGroup
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBEngineVersion
      MasterUsername: !Ref DBMasterUsername
      MasterUserPassword: !Ref DBMasterUserPassword
      VPCSecurityGroups:
        - !Ref DBSecurityGroup

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName: !Sub "${ProjectName}-DBSubnetGroup"
      DBSubnetGroupDescription: testgroup.
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2


Outputs:
  DBInstanceEndpointAddress:
    Value: !GetAtt DBInstance.Endpoint.Address
